export default () => ({
  instanceConfig: {
    context: {
      theme: 'senseish',
    },
  },
  genericObjects: [
    {
      getLayout() {
        return {
          qInfo: {
            qId: 'jZwmt',
            qType: 'treemap',
          },
          qMeta: {
            privileges: ['read', 'update', 'delete'],
          },
          qSelectionInfo: {},
          qHyperCube: {
            qSize: {
              qcx: 1,
              qcy: 27,
            },
            qDimensionInfo: [
              {
                qFallbackTitle: 'Dim1',
                qApprMaxGlyphCount: 1,
                qCardinal: 3,
                qSortIndicator: 'A',
                qGroupFallbackTitles: ['Dim1'],
                qGroupPos: 0,
                qStateCounts: {
                  qLocked: 0,
                  qSelected: 0,
                  qOption: 3,
                  qDeselected: 0,
                  qAlternative: 0,
                  qExcluded: 0,
                  qSelectedExcluded: 0,
                  qLockedExcluded: 0,
                },
                qTags: ['$ascii', '$text'],
                qDimensionType: 'D',
                qGrouping: 'N',
                qNumFormat: {
                  qType: 'U',
                  qnDec: 0,
                  qUseThou: 0,
                },
                qIsAutoFormat: true,
                qGroupFieldDefs: ['Dim1'],
                qMin: 'NaN',
                qMax: 'NaN',
                qAttrExprInfo: [],
                qAttrDimInfo: [],
                qCardinalities: {
                  qCardinal: 3,
                  qHypercubeCardinal: 3,
                  qAllValuesCardinal: -1,
                },
                autoSort: true,
                cId: 'emGPKJE',
                othersLabel: 'Others',
              },
              {
                qFallbackTitle: 'Dim2',
                qApprMaxGlyphCount: 1,
                qCardinal: 6,
                qSortIndicator: 'A',
                qGroupFallbackTitles: ['Dim2'],
                qGroupPos: 0,
                qStateCounts: {
                  qLocked: 0,
                  qSelected: 0,
                  qOption: 6,
                  qDeselected: 0,
                  qAlternative: 0,
                  qExcluded: 0,
                  qSelectedExcluded: 0,
                  qLockedExcluded: 0,
                },
                qTags: ['$ascii', '$text'],
                qDimensionType: 'D',
                qGrouping: 'N',
                qNumFormat: {
                  qType: 'U',
                  qnDec: 0,
                  qUseThou: 0,
                },
                qIsAutoFormat: true,
                qGroupFieldDefs: ['Dim2'],
                qMin: 'NaN',
                qMax: 'NaN',
                qAttrExprInfo: [],
                qAttrDimInfo: [],
                qCardinalities: {
                  qCardinal: 6,
                  qHypercubeCardinal: 7,
                  qAllValuesCardinal: -1,
                },
                autoSort: true,
                cId: 'sHVpGh',
                othersLabel: 'Others',
              },
              {
                qFallbackTitle: 'Dim3',
                qApprMaxGlyphCount: 1,
                qCardinal: 3,
                qSortIndicator: 'A',
                qGroupFallbackTitles: ['Dim3'],
                qGroupPos: 0,
                qStateCounts: {
                  qLocked: 0,
                  qSelected: 0,
                  qOption: 3,
                  qDeselected: 0,
                  qAlternative: 0,
                  qExcluded: 0,
                  qSelectedExcluded: 0,
                  qLockedExcluded: 0,
                },
                qTags: ['$ascii', '$text'],
                qDimensionType: 'D',
                qGrouping: 'N',
                qNumFormat: {
                  qType: 'U',
                  qnDec: 0,
                  qUseThou: 0,
                },
                qIsAutoFormat: true,
                qGroupFieldDefs: ['Dim3'],
                qMin: 'NaN',
                qMax: 'NaN',
                qAttrExprInfo: [],
                qAttrDimInfo: [],
                qCardinalities: {
                  qCardinal: 3,
                  qHypercubeCardinal: 5,
                  qAllValuesCardinal: -1,
                },
                autoSort: true,
                cId: 'cSbjh',
                othersLabel: 'Others',
              },
            ],
            qMeasureInfo: [
              {
                qFallbackTitle: 'Sum(Expression1)',
                qApprMaxGlyphCount: 8,
                qCardinal: 0,
                qSortIndicator: 'D',
                qNumFormat: {
                  qType: 'I',
                  qnDec: 0,
                  qUseThou: 1,
                  qFmt: '###0',
                  qDec: '.',
                },
                qMin: 344746,
                qMax: 3843628,
                qIsAutoFormat: true,
                qAttrExprInfo: [],
                qAttrDimInfo: [],
                qTrendLines: [],
                autoSort: true,
                cId: 'ScJnf',
                numFormatFromTemplate: true,
              },
            ],
            qEffectiveInterColumnSortOrder: [0, 1, 2],
            qGrandTotalRow: [],
            qDataPages: [],
            qPivotDataPages: [],
            qStackedDataPages: [
              {
                qData: [
                  {
                    qElemNo: 0,
                    qValue: 0,
                    qType: 'R',
                    qMaxPos: 37554258,
                    qMinNeg: 0,
                    qUp: 0,
                    qDown: 0,
                    qRow: 0,
                    qSubNodes: [
                      {
                        qText: 'C',
                        qElemNo: 0,
                        qValue: 'NaN',
                        qType: 'N',
                        qMaxPos: 20939283,
                        qMinNeg: 0,
                        qUp: 0,
                        qDown: 0,
                        qRow: 0,
                        qSubNodes: [
                          {
                            qElemNo: -1,
                            qValue: 'NaN',
                            qType: 'T',
                            qMaxPos: 0,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 0,
                            qSubNodes: [
                              {
                                qElemNo: -4,
                                qValue: 'NaN',
                                qType: 'E',
                                qMaxPos: 20939283,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 0,
                                qSubNodes: [
                                  {
                                    qText: '20939283',
                                    qElemNo: 0,
                                    qValue: 20939283,
                                    qType: 'V',
                                    qMaxPos: 0,
                                    qMinNeg: 0,
                                    qUp: 0,
                                    qDown: 0,
                                    qRow: 0,
                                    qSubNodes: [],
                                  },
                                ],
                              },
                            ],
                          },
                          {
                            qText: 'f',
                            qElemNo: 0,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 11524407,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 1,
                            qSubNodes: [
                              {
                                qElemNo: -1,
                                qValue: 'NaN',
                                qType: 'T',
                                qMaxPos: 11524407,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 1,
                                qSubNodes: [
                                  {
                                    qText: '11524407',
                                    qElemNo: 0,
                                    qValue: 11524407,
                                    qType: 'V',
                                    qMaxPos: 0,
                                    qMinNeg: 0,
                                    qUp: 0,
                                    qDown: 0,
                                    qRow: 1,
                                    qSubNodes: [],
                                  },
                                ],
                              },
                              {
                                qText: 'Z',
                                qElemNo: 2,
                                qValue: 'NaN',
                                qType: 'N',
                                qMaxPos: 3843628,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 2,
                                qSubNodes: [
                                  {
                                    qText: '3843628',
                                    qElemNo: 0,
                                    qValue: 3843628,
                                    qType: 'V',
                                    qMaxPos: 0,
                                    qMinNeg: 0,
                                    qUp: 0,
                                    qDown: 0,
                                    qRow: 2,
                                    qSubNodes: [],
                                  },
                                ],
                              },
                              {
                                qText: 'Y',
                                qElemNo: 1,
                                qValue: 'NaN',
                                qType: 'N',
                                qMaxPos: 3843008,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 3,
                                qSubNodes: [
                                  {
                                    qText: '3843008',
                                    qElemNo: 0,
                                    qValue: 3843008,
                                    qType: 'V',
                                    qMaxPos: 0,
                                    qMinNeg: 0,
                                    qUp: 0,
                                    qDown: 0,
                                    qRow: 3,
                                    qSubNodes: [],
                                  },
                                ],
                              },
                              {
                                qText: 'X',
                                qElemNo: 0,
                                qValue: 'NaN',
                                qType: 'N',
                                qMaxPos: 3837771,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 4,
                                qSubNodes: [
                                  {
                                    qText: '3837771',
                                    qElemNo: 0,
                                    qValue: 3837771,
                                    qType: 'V',
                                    qMaxPos: 0,
                                    qMinNeg: 0,
                                    qUp: 0,
                                    qDown: 0,
                                    qRow: 4,
                                    qSubNodes: [],
                                  },
                                ],
                              },
                            ],
                          },
                          {
                            qText: 'e',
                            qElemNo: 5,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 9414876,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 5,
                            qSubNodes: [
                              {
                                qElemNo: -1,
                                qValue: 'NaN',
                                qType: 'T',
                                qMaxPos: 9414876,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 5,
                                qSubNodes: [
                                  {
                                    qText: '9414876',
                                    qElemNo: 0,
                                    qValue: 9414876,
                                    qType: 'V',
                                    qMaxPos: 0,
                                    qMinNeg: 0,
                                    qUp: 0,
                                    qDown: 0,
                                    qRow: 5,
                                    qSubNodes: [],
                                  },
                                ],
                              },
                              {
                                qText: 'X',
                                qElemNo: 0,
                                qValue: 'NaN',
                                qType: 'N',
                                qMaxPos: 3206027,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 6,
                                qSubNodes: [
                                  {
                                    qText: '3206027',
                                    qElemNo: 0,
                                    qValue: 3206027,
                                    qType: 'V',
                                    qMaxPos: 0,
                                    qMinNeg: 0,
                                    qUp: 0,
                                    qDown: 0,
                                    qRow: 6,
                                    qSubNodes: [],
                                  },
                                ],
                              },
                              {
                                qText: 'Y',
                                qElemNo: 1,
                                qValue: 'NaN',
                                qType: 'N',
                                qMaxPos: 3129401,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 7,
                                qSubNodes: [
                                  {
                                    qText: '3129401',
                                    qElemNo: 0,
                                    qValue: 3129401,
                                    qType: 'V',
                                    qMaxPos: 0,
                                    qMinNeg: 0,
                                    qUp: 0,
                                    qDown: 0,
                                    qRow: 7,
                                    qSubNodes: [],
                                  },
                                ],
                              },
                              {
                                qText: 'Z',
                                qElemNo: 2,
                                qValue: 'NaN',
                                qType: 'N',
                                qMaxPos: 3079448,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 8,
                                qSubNodes: [
                                  {
                                    qText: '3079448',
                                    qElemNo: 0,
                                    qValue: 3079448,
                                    qType: 'V',
                                    qMaxPos: 0,
                                    qMinNeg: 0,
                                    qUp: 0,
                                    qDown: 0,
                                    qRow: 8,
                                    qSubNodes: [],
                                  },
                                ],
                              },
                            ],
                          },
                        ],
                      },
                      {
                        qText: 'B',
                        qElemNo: 2,
                        qValue: 'NaN',
                        qType: 'N',
                        qMaxPos: 12464673,
                        qMinNeg: 0,
                        qUp: 0,
                        qDown: 0,
                        qRow: 9,
                        qSubNodes: [
                          {
                            qElemNo: -1,
                            qValue: 'NaN',
                            qType: 'T',
                            qMaxPos: 0,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 9,
                            qSubNodes: [
                              {
                                qElemNo: -4,
                                qValue: 'NaN',
                                qType: 'E',
                                qMaxPos: 12464673,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 9,
                                qSubNodes: [
                                  {
                                    qText: '12464673',
                                    qElemNo: 0,
                                    qValue: 12464673,
                                    qType: 'V',
                                    qMaxPos: 0,
                                    qMinNeg: 0,
                                    qUp: 0,
                                    qDown: 0,
                                    qRow: 9,
                                    qSubNodes: [],
                                  },
                                ],
                              },
                            ],
                          },
                          {
                            qText: 'd',
                            qElemNo: 2,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 7262292,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 10,
                            qSubNodes: [
                              {
                                qElemNo: -1,
                                qValue: 'NaN',
                                qType: 'T',
                                qMaxPos: 7262292,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 10,
                                qSubNodes: [
                                  {
                                    qText: '7262292',
                                    qElemNo: 0,
                                    qValue: 7262292,
                                    qType: 'V',
                                    qMaxPos: 0,
                                    qMinNeg: 0,
                                    qUp: 0,
                                    qDown: 0,
                                    qRow: 10,
                                    qSubNodes: [],
                                  },
                                ],
                              },
                              {
                                qText: 'X',
                                qElemNo: 0,
                                qValue: 'NaN',
                                qType: 'N',
                                qMaxPos: 2453337,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 11,
                                qSubNodes: [
                                  {
                                    qText: '2453337',
                                    qElemNo: 0,
                                    qValue: 2453337,
                                    qType: 'V',
                                    qMaxPos: 0,
                                    qMinNeg: 0,
                                    qUp: 0,
                                    qDown: 0,
                                    qRow: 11,
                                    qSubNodes: [],
                                  },
                                ],
                              },
                              {
                                qText: 'Z',
                                qElemNo: 2,
                                qValue: 'NaN',
                                qType: 'N',
                                qMaxPos: 2428015,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 12,
                                qSubNodes: [
                                  {
                                    qText: '2428015',
                                    qElemNo: 0,
                                    qValue: 2428015,
                                    qType: 'V',
                                    qMaxPos: 0,
                                    qMinNeg: 0,
                                    qUp: 0,
                                    qDown: 0,
                                    qRow: 12,
                                    qSubNodes: [],
                                  },
                                ],
                              },
                              {
                                qText: 'Y',
                                qElemNo: 1,
                                qValue: 'NaN',
                                qType: 'N',
                                qMaxPos: 2380940,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 13,
                                qSubNodes: [
                                  {
                                    qText: '2380940',
                                    qElemNo: 0,
                                    qValue: 2380940,
                                    qType: 'V',
                                    qMaxPos: 0,
                                    qMinNeg: 0,
                                    qUp: 0,
                                    qDown: 0,
                                    qRow: 13,
                                    qSubNodes: [],
                                  },
                                ],
                              },
                            ],
                          },
                          {
                            qText: 'c',
                            qElemNo: 3,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 5202381,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 14,
                            qSubNodes: [
                              {
                                qElemNo: -1,
                                qValue: 'NaN',
                                qType: 'T',
                                qMaxPos: 5202381,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 14,
                                qSubNodes: [
                                  {
                                    qText: '5202381',
                                    qElemNo: 0,
                                    qValue: 5202381,
                                    qType: 'V',
                                    qMaxPos: 0,
                                    qMinNeg: 0,
                                    qUp: 0,
                                    qDown: 0,
                                    qRow: 14,
                                    qSubNodes: [],
                                  },
                                ],
                              },
                              {
                                qText: 'Y',
                                qElemNo: 1,
                                qValue: 'NaN',
                                qType: 'N',
                                qMaxPos: 1739879,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 15,
                                qSubNodes: [
                                  {
                                    qText: '1739879',
                                    qElemNo: 0,
                                    qValue: 1739879,
                                    qType: 'V',
                                    qMaxPos: 0,
                                    qMinNeg: 0,
                                    qUp: 0,
                                    qDown: 0,
                                    qRow: 15,
                                    qSubNodes: [],
                                  },
                                ],
                              },
                              {
                                qText: 'X',
                                qElemNo: 0,
                                qValue: 'NaN',
                                qType: 'N',
                                qMaxPos: 1734674,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 16,
                                qSubNodes: [
                                  {
                                    qText: '1734674',
                                    qElemNo: 0,
                                    qValue: 1734674,
                                    qType: 'V',
                                    qMaxPos: 0,
                                    qMinNeg: 0,
                                    qUp: 0,
                                    qDown: 0,
                                    qRow: 16,
                                    qSubNodes: [],
                                  },
                                ],
                              },
                              {
                                qText: 'Z',
                                qElemNo: 2,
                                qValue: 'NaN',
                                qType: 'N',
                                qMaxPos: 1727828,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 17,
                                qSubNodes: [
                                  {
                                    qText: '1727828',
                                    qElemNo: 0,
                                    qValue: 1727828,
                                    qType: 'V',
                                    qMaxPos: 0,
                                    qMinNeg: 0,
                                    qUp: 0,
                                    qDown: 0,
                                    qRow: 17,
                                    qSubNodes: [],
                                  },
                                ],
                              },
                            ],
                          },
                        ],
                      },
                      {
                        qText: 'A',
                        qElemNo: 1,
                        qValue: 'NaN',
                        qType: 'N',
                        qMaxPos: 4150302,
                        qMinNeg: 0,
                        qUp: 0,
                        qDown: 0,
                        qRow: 18,
                        qSubNodes: [
                          {
                            qElemNo: -1,
                            qValue: 'NaN',
                            qType: 'T',
                            qMaxPos: 0,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 18,
                            qSubNodes: [
                              {
                                qElemNo: -4,
                                qValue: 'NaN',
                                qType: 'E',
                                qMaxPos: 4150302,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 18,
                                qSubNodes: [
                                  {
                                    qText: '4150302',
                                    qElemNo: 0,
                                    qValue: 4150302,
                                    qType: 'V',
                                    qMaxPos: 0,
                                    qMinNeg: 0,
                                    qUp: 0,
                                    qDown: 0,
                                    qRow: 18,
                                    qSubNodes: [],
                                  },
                                ],
                              },
                            ],
                          },
                          {
                            qText: 'b',
                            qElemNo: 1,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 3105815,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 19,
                            qSubNodes: [
                              {
                                qElemNo: -1,
                                qValue: 'NaN',
                                qType: 'T',
                                qMaxPos: 3105815,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 19,
                                qSubNodes: [
                                  {
                                    qText: '3105815',
                                    qElemNo: 0,
                                    qValue: 3105815,
                                    qType: 'V',
                                    qMaxPos: 0,
                                    qMinNeg: 0,
                                    qUp: 0,
                                    qDown: 0,
                                    qRow: 19,
                                    qSubNodes: [],
                                  },
                                ],
                              },
                              {
                                qText: 'Z',
                                qElemNo: 2,
                                qValue: 'NaN',
                                qType: 'N',
                                qMaxPos: 1037825,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 20,
                                qSubNodes: [
                                  {
                                    qText: '1037825',
                                    qElemNo: 0,
                                    qValue: 1037825,
                                    qType: 'V',
                                    qMaxPos: 0,
                                    qMinNeg: 0,
                                    qUp: 0,
                                    qDown: 0,
                                    qRow: 20,
                                    qSubNodes: [],
                                  },
                                ],
                              },
                              {
                                qText: 'X',
                                qElemNo: 0,
                                qValue: 'NaN',
                                qType: 'N',
                                qMaxPos: 1037025,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 21,
                                qSubNodes: [
                                  {
                                    qText: '1037025',
                                    qElemNo: 0,
                                    qValue: 1037025,
                                    qType: 'V',
                                    qMaxPos: 0,
                                    qMinNeg: 0,
                                    qUp: 0,
                                    qDown: 0,
                                    qRow: 21,
                                    qSubNodes: [],
                                  },
                                ],
                              },
                              {
                                qText: 'Y',
                                qElemNo: 1,
                                qValue: 'NaN',
                                qType: 'N',
                                qMaxPos: 1030965,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 22,
                                qSubNodes: [
                                  {
                                    qText: '1030965',
                                    qElemNo: 0,
                                    qValue: 1030965,
                                    qType: 'V',
                                    qMaxPos: 0,
                                    qMinNeg: 0,
                                    qUp: 0,
                                    qDown: 0,
                                    qRow: 22,
                                    qSubNodes: [],
                                  },
                                ],
                              },
                            ],
                          },
                          {
                            qText: 'a',
                            qElemNo: 4,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 1044487,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 23,
                            qSubNodes: [
                              {
                                qElemNo: -1,
                                qValue: 'NaN',
                                qType: 'T',
                                qMaxPos: 1044487,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 23,
                                qSubNodes: [
                                  {
                                    qText: '1044487',
                                    qElemNo: 0,
                                    qValue: 1044487,
                                    qType: 'V',
                                    qMaxPos: 0,
                                    qMinNeg: 0,
                                    qUp: 0,
                                    qDown: 0,
                                    qRow: 23,
                                    qSubNodes: [],
                                  },
                                ],
                              },
                              {
                                qText: 'Z',
                                qElemNo: 2,
                                qValue: 'NaN',
                                qType: 'N',
                                qMaxPos: 353444,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 24,
                                qSubNodes: [
                                  {
                                    qText: '353444',
                                    qElemNo: 0,
                                    qValue: 353444,
                                    qType: 'V',
                                    qMaxPos: 0,
                                    qMinNeg: 0,
                                    qUp: 0,
                                    qDown: 0,
                                    qRow: 24,
                                    qSubNodes: [],
                                  },
                                ],
                              },
                              {
                                qText: 'Y',
                                qElemNo: 1,
                                qValue: 'NaN',
                                qType: 'N',
                                qMaxPos: 346297,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 25,
                                qSubNodes: [
                                  {
                                    qText: '346297',
                                    qElemNo: 0,
                                    qValue: 346297,
                                    qType: 'V',
                                    qMaxPos: 0,
                                    qMinNeg: 0,
                                    qUp: 0,
                                    qDown: 0,
                                    qRow: 25,
                                    qSubNodes: [],
                                  },
                                ],
                              },
                              {
                                qText: 'X',
                                qElemNo: 0,
                                qValue: 'NaN',
                                qType: 'N',
                                qMaxPos: 344746,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 26,
                                qSubNodes: [
                                  {
                                    qText: '344746',
                                    qElemNo: 0,
                                    qValue: 344746,
                                    qType: 'V',
                                    qMaxPos: 0,
                                    qMinNeg: 0,
                                    qUp: 0,
                                    qDown: 0,
                                    qRow: 26,
                                    qSubNodes: [],
                                  },
                                ],
                              },
                            ],
                          },
                        ],
                      },
                    ],
                  },
                ],
                qArea: {
                  qLeft: 0,
                  qTop: 0,
                  qWidth: 3,
                  qHeight: 3,
                },
              },
            ],
            qMode: 'K',
            qNoOfLeftDims: 3,
            qIndentMode: true,
            qTreeNodesOnDim: [],
            qColumnOrder: [],
          },
          script: '',
          showTitles: true,
          title: '',
          subtitle: '',
          footnote: '',
          disableNavMenu: false,
          showDetails: true,
          showDetailsExpression: false,
          showDisclaimer: true,
          labels: {
            auto: true,
            headers: true,
            overlay: true,
            leaves: true,
            values: false,
          },
          color: {
            auto: true,
            mode: 'primary',
            formatting: {
              numFormatFromTemplate: true,
            },
            useBaseColors: 'off',
            paletteColor: {
              index: 6,
            },
            useDimColVal: true,
            useMeasureGradient: true,
            persistent: true,
            expressionIsColor: true,
            expressionLabel: '',
            measureScheme: 'sg',
            reverseScheme: false,
            dimensionScheme: '12',
            autoMinMax: true,
            measureMin: 0,
            measureMax: 10,
          },
          legend: {
            show: false,
            dock: 'auto',
            showTitle: true,
          },
          tooltip: {
            auto: true,
            hideBasic: false,
            chart: {
              style: {
                size: 'medium',
              },
            },
          },
          visualization: 'treemap',
        };
      },
      getEffectiveProperties: {},
    },
  ],
});
