export default () => ({
  instanceConfig: {
    context: {
      theme: 'senseish',
    },
  },
  genericObjects: [
    {
      getLayout() {
        return {
          qInfo: {
            qId: 'pJHkmK',
            qType: 'treemap',
          },
          qMeta: {
            privileges: ['read', 'update', 'delete'],
          },
          qSelectionInfo: {
            qInSelections: false,
            qMadeSelections: false,
          },
          qHyperCube: {
            qSize: {
              qcx: 1,
              qcy: 50,
            },
            qDimensionInfo: [
              {
                qFallbackTitle: 'Region Name',
                qApprMaxGlyphCount: 9,
                qCardinal: 4,
                qSortIndicator: 'A',
                qGroupFallbackTitles: ['Region Name'],
                qGroupPos: 0,
                qStateCounts: {
                  qLocked: 0,
                  qSelected: 0,
                  qOption: 4,
                  qDeselected: 0,
                  qAlternative: 0,
                  qExcluded: 0,
                  qSelectedExcluded: 0,
                  qLockedExcluded: 0,
                },
                qTags: ['$ascii', '$text'],
                qDimensionType: 'D',
                qGrouping: 'N',
                qNumFormat: {
                  qType: 'U',
                  qnDec: 0,
                  qUseThou: 0,
                },
                qIsAutoFormat: true,
                qGroupFieldDefs: ['Region Name'],
                qMin: 'NaN',
                qMax: 'NaN',
                qAttrExprInfo: [],
                qAttrDimInfo: [],
                qCardinalities: {
                  qCardinal: 4,
                  qHypercubeCardinal: 4,
                  qAllValuesCardinal: -1,
                },
                autoSort: true,
                cId: 'HuQWmW',
                othersLabel: 'Others',
              },
              {
                qFallbackTitle: 'state_name',
                qApprMaxGlyphCount: 14,
                qCardinal: 46,
                qSortIndicator: 'A',
                qGroupFallbackTitles: ['state_name'],
                qGroupPos: 0,
                qStateCounts: {
                  qLocked: 0,
                  qSelected: 0,
                  qOption: 46,
                  qDeselected: 0,
                  qAlternative: 0,
                  qExcluded: 0,
                  qSelectedExcluded: 0,
                  qLockedExcluded: 0,
                },
                qTags: ['$ascii', '$text'],
                qDimensionType: 'D',
                qGrouping: 'N',
                qNumFormat: {
                  qType: 'U',
                  qnDec: 0,
                  qUseThou: 0,
                },
                qIsAutoFormat: true,
                qGroupFieldDefs: ['state_name'],
                qMin: 'NaN',
                qMax: 'NaN',
                qAttrExprInfo: [
                  {
                    qMin: 0,
                    qMax: 12213258.03,
                    qFallbackTitle: 'Sum([Actual Amount])',
                    qMinText: '0',
                    qMaxText: '12213258.03',
                    qNumFormat: {
                      qType: 'U',
                      qnDec: 0,
                      qUseThou: 0,
                    },
                    qIsAutoFormat: true,
                    id: 'colorByAlternative',
                    label: 'Sum([Actual Amount])',
                  },
                ],
                qAttrDimInfo: [],
                qCardinalities: {
                  qCardinal: 46,
                  qHypercubeCardinal: 47,
                  qAllValuesCardinal: -1,
                },
                autoSort: true,
                cId: 'EpJqV',
                othersLabel: 'Others',
              },
            ],
            qMeasureInfo: [
              {
                qFallbackTitle: 'Sum([Actual Amount])',
                qApprMaxGlyphCount: 11,
                qCardinal: 0,
                qSortIndicator: 'D',
                qNumFormat: {
                  qType: 'U',
                  qnDec: 0,
                  qUseThou: 0,
                },
                qMin: 0,
                qMax: 12213258.03,
                qIsAutoFormat: true,
                qAttrExprInfo: [],
                qAttrDimInfo: [],
                qTrendLines: [],
                autoSort: true,
                cId: 'LYXjH',
                numFormatFromTemplate: true,
              },
            ],
            qEffectiveInterColumnSortOrder: [0, 1],
            qGrandTotalRow: [],
            qDataPages: [],
            qPivotDataPages: [],
            qStackedDataPages: [
              {
                qData: [
                  {
                    qElemNo: 0,
                    qValue: 0,
                    qType: 'R',
                    qMaxPos: 46379136.089999996,
                    qMinNeg: 0,
                    qUp: 0,
                    qDown: 0,
                    qRow: 0,
                    qSubNodes: [
                      {
                        qText: 'Central',
                        qElemNo: 3,
                        qValue: 'NaN',
                        qType: 'N',
                        qMaxPos: 21598649.599999998,
                        qMinNeg: 0,
                        qUp: 0,
                        qDown: 0,
                        qRow: 0,
                        qSubNodes: [
                          {
                            qElemNo: -1,
                            qValue: 'NaN',
                            qType: 'T',
                            qMaxPos: 21598649.600000005,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 0,
                            qSubNodes: [
                              {
                                qText: '21598649.6',
                                qElemNo: 0,
                                qValue: 21598649.600000005,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 0,
                                qSubNodes: [],
                              },
                            ],
                            qAttrExps: {
                              qValues: [
                                {
                                  qText: '21598649.6',
                                  qNum: 21598649.600000005,
                                },
                              ],
                            },
                          },
                          {
                            qText: 'Ohio',
                            qElemNo: 31,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 12213258.03,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 1,
                            qSubNodes: [
                              {
                                qText: '12213258.03',
                                qElemNo: 0,
                                qValue: 12213258.03,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 1,
                                qSubNodes: [],
                              },
                            ],
                            qAttrExps: {
                              qValues: [
                                {
                                  qText: '12213258.03',
                                  qNum: 12213258.03,
                                },
                              ],
                            },
                          },
                          {
                            qText: 'Michigan',
                            qElemNo: 19,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 2220622.7000000016,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 2,
                            qSubNodes: [
                              {
                                qText: '2220622.7',
                                qElemNo: 0,
                                qValue: 2220622.7000000016,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 2,
                                qSubNodes: [],
                              },
                            ],
                            qAttrExps: {
                              qValues: [
                                {
                                  qText: '2220622.7',
                                  qNum: 2220622.7000000016,
                                },
                              ],
                            },
                          },
                          {
                            qText: 'Iowa',
                            qElemNo: 8,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 2113982.5800000005,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 3,
                            qSubNodes: [
                              {
                                qText: '2113982.58',
                                qElemNo: 0,
                                qValue: 2113982.5800000005,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 3,
                                qSubNodes: [],
                              },
                            ],
                            qAttrExps: {
                              qValues: [
                                {
                                  qText: '2113982.58',
                                  qNum: 2113982.5800000005,
                                },
                              ],
                            },
                          },
                          {
                            qText: 'Indiana',
                            qElemNo: 11,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 1197285.7200000004,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 4,
                            qSubNodes: [
                              {
                                qText: '1197285.72',
                                qElemNo: 0,
                                qValue: 1197285.7200000004,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 4,
                                qSubNodes: [],
                              },
                            ],
                            qAttrExps: {
                              qValues: [
                                {
                                  qText: '1197285.72',
                                  qNum: 1197285.7200000004,
                                },
                              ],
                            },
                          },
                          {
                            qText: 'Illinois',
                            qElemNo: 10,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 1022772.9799999999,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 5,
                            qSubNodes: [
                              {
                                qText: '1022772.98',
                                qElemNo: 0,
                                qValue: 1022772.9799999999,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 5,
                                qSubNodes: [],
                              },
                            ],
                            qAttrExps: {
                              qValues: [
                                {
                                  qText: '1022772.98',
                                  qNum: 1022772.9799999999,
                                },
                              ],
                            },
                          },
                          {
                            qText: 'Missouri',
                            qElemNo: 21,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 903755.7200000001,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 6,
                            qSubNodes: [
                              {
                                qText: '903755.72',
                                qElemNo: 0,
                                qValue: 903755.7200000001,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 6,
                                qSubNodes: [],
                              },
                            ],
                            qAttrExps: {
                              qValues: [
                                {
                                  qText: '903755.72',
                                  qNum: 903755.7200000001,
                                },
                              ],
                            },
                          },
                          {
                            qText: 'Wisconsin',
                            qElemNo: 43,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 562751.7600000001,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 7,
                            qSubNodes: [
                              {
                                qText: '562751.76',
                                qElemNo: 0,
                                qValue: 562751.7600000001,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 7,
                                qSubNodes: [],
                              },
                            ],
                            qAttrExps: {
                              qValues: [
                                {
                                  qText: '562751.76',
                                  qNum: 562751.7600000001,
                                },
                              ],
                            },
                          },
                          {
                            qText: 'Kansas',
                            qElemNo: 12,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 514023.83,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 8,
                            qSubNodes: [
                              {
                                qText: '514023.83',
                                qElemNo: 0,
                                qValue: 514023.83,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 8,
                                qSubNodes: [],
                              },
                            ],
                            qAttrExps: {
                              qValues: [
                                {
                                  qText: '514023.83',
                                  qNum: 514023.83,
                                },
                              ],
                            },
                          },
                          {
                            qText: 'South Dakota',
                            qElemNo: 37,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 385689.2399999999,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 9,
                            qSubNodes: [
                              {
                                qText: '385689.24',
                                qElemNo: 0,
                                qValue: 385689.2399999999,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 9,
                                qSubNodes: [],
                              },
                            ],
                            qAttrExps: {
                              qValues: [
                                {
                                  qText: '385689.24',
                                  qNum: 385689.2399999999,
                                },
                              ],
                            },
                          },
                          {
                            qText: 'Minnesota',
                            qElemNo: 20,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 294847.4100000001,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 10,
                            qSubNodes: [
                              {
                                qText: '294847.41',
                                qElemNo: 0,
                                qValue: 294847.4100000001,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 10,
                                qSubNodes: [],
                              },
                            ],
                            qAttrExps: {
                              qValues: [
                                {
                                  qText: '294847.41',
                                  qNum: 294847.4100000001,
                                },
                              ],
                            },
                          },
                          {
                            qText: 'Nebraska',
                            qElemNo: 25,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 169659.63,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 11,
                            qSubNodes: [
                              {
                                qText: '169659.63',
                                qElemNo: 0,
                                qValue: 169659.63,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 11,
                                qSubNodes: [],
                              },
                            ],
                            qAttrExps: {
                              qValues: [
                                {
                                  qText: '169659.63',
                                  qNum: 169659.63,
                                },
                              ],
                            },
                          },
                        ],
                      },
                      {
                        qText: 'Western',
                        qElemNo: 0,
                        qValue: 'NaN',
                        qType: 'N',
                        qMaxPos: 11428356.010000002,
                        qMinNeg: 0,
                        qUp: 0,
                        qDown: 0,
                        qRow: 12,
                        qSubNodes: [
                          {
                            qElemNo: -1,
                            qValue: 'NaN',
                            qType: 'T',
                            qMaxPos: 11428356.01,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 12,
                            qSubNodes: [
                              {
                                qText: '11428356.01',
                                qElemNo: 0,
                                qValue: 11428356.01,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 12,
                                qSubNodes: [],
                              },
                            ],
                            qAttrExps: {
                              qValues: [
                                {
                                  qText: '11428356.01',
                                  qNum: 11428356.01,
                                },
                              ],
                            },
                          },
                          {
                            qText: 'California',
                            qElemNo: 4,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 4969952.959999999,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 13,
                            qSubNodes: [
                              {
                                qText: '4969952.96',
                                qElemNo: 0,
                                qValue: 4969952.959999999,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 13,
                                qSubNodes: [],
                              },
                            ],
                            qAttrExps: {
                              qValues: [
                                {
                                  qText: '4969952.96',
                                  qNum: 4969952.959999999,
                                },
                              ],
                            },
                          },
                          {
                            qText: 'Utah',
                            qElemNo: 40,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 2249127.88,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 14,
                            qSubNodes: [
                              {
                                qText: '2249127.88',
                                qElemNo: 0,
                                qValue: 2249127.88,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 14,
                                qSubNodes: [],
                              },
                            ],
                            qAttrExps: {
                              qValues: [
                                {
                                  qText: '2249127.88',
                                  qNum: 2249127.88,
                                },
                              ],
                            },
                          },
                          {
                            qText: 'Oregon',
                            qElemNo: 33,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 1345361.7700000005,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 15,
                            qSubNodes: [
                              {
                                qText: '1345361.77',
                                qElemNo: 0,
                                qValue: 1345361.7700000005,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 15,
                                qSubNodes: [],
                              },
                            ],
                            qAttrExps: {
                              qValues: [
                                {
                                  qText: '1345361.77',
                                  qNum: 1345361.7700000005,
                                },
                              ],
                            },
                          },
                          {
                            qText: 'Nevada',
                            qElemNo: 29,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 1288612.08,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 16,
                            qSubNodes: [
                              {
                                qText: '1288612.08',
                                qElemNo: 0,
                                qValue: 1288612.08,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 16,
                                qSubNodes: [],
                              },
                            ],
                            qAttrExps: {
                              qValues: [
                                {
                                  qText: '1288612.08',
                                  qNum: 1288612.08,
                                },
                              ],
                            },
                          },
                          {
                            qText: 'Washington',
                            qElemNo: 42,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 776259.9799999997,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 17,
                            qSubNodes: [
                              {
                                qText: '776259.98',
                                qElemNo: 0,
                                qValue: 776259.9799999997,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 17,
                                qSubNodes: [],
                              },
                            ],
                            qAttrExps: {
                              qValues: [
                                {
                                  qText: '776259.98',
                                  qNum: 776259.9799999997,
                                },
                              ],
                            },
                          },
                          {
                            qText: 'Idaho',
                            qElemNo: 9,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 569583.84,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 18,
                            qSubNodes: [
                              {
                                qText: '569583.84',
                                qElemNo: 0,
                                qValue: 569583.84,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 18,
                                qSubNodes: [],
                              },
                            ],
                            qAttrExps: {
                              qValues: [
                                {
                                  qText: '569583.84',
                                  qNum: 569583.84,
                                },
                              ],
                            },
                          },
                          {
                            qText: 'Arizona',
                            qElemNo: 3,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 123923.64000000004,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 19,
                            qSubNodes: [
                              {
                                qText: '123923.64',
                                qElemNo: 0,
                                qValue: 123923.64000000004,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 19,
                                qSubNodes: [],
                              },
                            ],
                            qAttrExps: {
                              qValues: [
                                {
                                  qText: '123923.64',
                                  qNum: 123923.64000000004,
                                },
                              ],
                            },
                          },
                          {
                            qText: 'Colorado',
                            qElemNo: 5,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 76717.93000000001,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 20,
                            qSubNodes: [
                              {
                                qText: '76717.93',
                                qElemNo: 0,
                                qValue: 76717.93000000001,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 20,
                                qSubNodes: [],
                              },
                            ],
                            qAttrExps: {
                              qValues: [
                                {
                                  qText: '76717.93',
                                  qNum: 76717.93000000001,
                                },
                              ],
                            },
                          },
                          {
                            qText: 'Montana',
                            qElemNo: 23,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 14893.21,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 21,
                            qSubNodes: [
                              {
                                qText: '14893.21',
                                qElemNo: 0,
                                qValue: 14893.21,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 21,
                                qSubNodes: [],
                              },
                            ],
                            qAttrExps: {
                              qValues: [
                                {
                                  qText: '14893.21',
                                  qNum: 14893.21,
                                },
                              ],
                            },
                          },
                          {
                            qText: 'Alaska',
                            qElemNo: 0,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 13922.72,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 22,
                            qSubNodes: [
                              {
                                qText: '13922.72',
                                qElemNo: 0,
                                qValue: 13922.72,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 22,
                                qSubNodes: [],
                              },
                            ],
                            qAttrExps: {
                              qValues: [
                                {
                                  qText: '13922.72',
                                  qNum: 13922.72,
                                },
                              ],
                            },
                          },
                          {
                            qText: 'New Mexico',
                            qElemNo: 28,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 0,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 23,
                            qSubNodes: [
                              {
                                qText: '0',
                                qElemNo: 0,
                                qValue: 0,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 23,
                                qSubNodes: [],
                              },
                            ],
                            qAttrExps: {
                              qValues: [
                                {
                                  qText: '0',
                                  qNum: 0,
                                },
                              ],
                            },
                          },
                          {
                            qText: 'Wyoming',
                            qElemNo: 45,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 0,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 24,
                            qSubNodes: [
                              {
                                qText: '0',
                                qElemNo: 0,
                                qValue: 0,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 24,
                                qSubNodes: [],
                              },
                            ],
                            qAttrExps: {
                              qValues: [
                                {
                                  qText: '0',
                                  qNum: 0,
                                },
                              ],
                            },
                          },
                        ],
                      },
                      {
                        qText: 'Southern',
                        qElemNo: 1,
                        qValue: 'NaN',
                        qType: 'N',
                        qMaxPos: 9269478.349999998,
                        qMinNeg: 0,
                        qUp: 0,
                        qDown: 0,
                        qRow: 25,
                        qSubNodes: [
                          {
                            qElemNo: -1,
                            qValue: 'NaN',
                            qType: 'T',
                            qMaxPos: 9269478.350000005,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 25,
                            qSubNodes: [
                              {
                                qText: '9269478.35',
                                qElemNo: 0,
                                qValue: 9269478.350000005,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 25,
                                qSubNodes: [],
                              },
                            ],
                            qAttrExps: {
                              qValues: [
                                {
                                  qText: '9269478.35',
                                  qNum: 9269478.350000005,
                                },
                              ],
                            },
                          },
                          {
                            qText: 'Texas',
                            qElemNo: 39,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 5218374.989999999,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 26,
                            qSubNodes: [
                              {
                                qText: '5218374.99',
                                qElemNo: 0,
                                qValue: 5218374.989999999,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 26,
                                qSubNodes: [],
                              },
                            ],
                            qAttrExps: {
                              qValues: [
                                {
                                  qText: '5218374.99',
                                  qNum: 5218374.989999999,
                                },
                              ],
                            },
                          },
                          {
                            qText: 'Mississippi',
                            qElemNo: 22,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 864212.9400000001,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 27,
                            qSubNodes: [
                              {
                                qText: '864212.94',
                                qElemNo: 0,
                                qValue: 864212.9400000001,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 27,
                                qSubNodes: [],
                              },
                            ],
                            qAttrExps: {
                              qValues: [
                                {
                                  qText: '864212.94',
                                  qNum: 864212.9400000001,
                                },
                              ],
                            },
                          },
                          {
                            qText: 'Florida',
                            qElemNo: 6,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 779704.92,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 28,
                            qSubNodes: [
                              {
                                qText: '779704.92',
                                qElemNo: 0,
                                qValue: 779704.92,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 28,
                                qSubNodes: [],
                              },
                            ],
                            qAttrExps: {
                              qValues: [
                                {
                                  qText: '779704.92',
                                  qNum: 779704.92,
                                },
                              ],
                            },
                          },
                          {
                            qText: 'North Carolina',
                            qElemNo: 24,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 595377.5900000001,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 29,
                            qSubNodes: [
                              {
                                qText: '595377.59',
                                qElemNo: 0,
                                qValue: 595377.5900000001,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 29,
                                qSubNodes: [],
                              },
                            ],
                            qAttrExps: {
                              qValues: [
                                {
                                  qText: '595377.59',
                                  qNum: 595377.5900000001,
                                },
                              ],
                            },
                          },
                          {
                            qText: 'Oklahoma',
                            qElemNo: 32,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 383746.7000000001,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 30,
                            qSubNodes: [
                              {
                                qText: '383746.7',
                                qElemNo: 0,
                                qValue: 383746.7000000001,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 30,
                                qSubNodes: [],
                              },
                            ],
                            qAttrExps: {
                              qValues: [
                                {
                                  qText: '383746.7',
                                  qNum: 383746.7000000001,
                                },
                              ],
                            },
                          },
                          {
                            qText: 'Louisiana',
                            qElemNo: 14,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 341680.46999999986,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 31,
                            qSubNodes: [
                              {
                                qText: '341680.47',
                                qElemNo: 0,
                                qValue: 341680.46999999986,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 31,
                                qSubNodes: [],
                              },
                            ],
                            qAttrExps: {
                              qValues: [
                                {
                                  qText: '341680.47',
                                  qNum: 341680.46999999986,
                                },
                              ],
                            },
                          },
                          {
                            qText: 'Arkansas',
                            qElemNo: 2,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 308144.01999999996,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 32,
                            qSubNodes: [
                              {
                                qText: '308144.02',
                                qElemNo: 0,
                                qValue: 308144.01999999996,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 32,
                                qSubNodes: [],
                              },
                            ],
                            qAttrExps: {
                              qValues: [
                                {
                                  qText: '308144.02',
                                  qNum: 308144.01999999996,
                                },
                              ],
                            },
                          },
                          {
                            qText: 'Kentucky',
                            qElemNo: 13,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 290856.13999999996,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 33,
                            qSubNodes: [
                              {
                                qText: '290856.14',
                                qElemNo: 0,
                                qValue: 290856.13999999996,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 33,
                                qSubNodes: [],
                              },
                            ],
                            qAttrExps: {
                              qValues: [
                                {
                                  qText: '290856.14',
                                  qNum: 290856.13999999996,
                                },
                              ],
                            },
                          },
                          {
                            qText: 'Tennessee',
                            qElemNo: 38,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 250719.53,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 34,
                            qSubNodes: [
                              {
                                qText: '250719.53',
                                qElemNo: 0,
                                qValue: 250719.53,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 34,
                                qSubNodes: [],
                              },
                            ],
                            qAttrExps: {
                              qValues: [
                                {
                                  qText: '250719.53',
                                  qNum: 250719.53,
                                },
                              ],
                            },
                          },
                          {
                            qText: 'Alabama',
                            qElemNo: 1,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 171187.94,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 35,
                            qSubNodes: [
                              {
                                qText: '171187.94',
                                qElemNo: 0,
                                qValue: 171187.94,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 35,
                                qSubNodes: [],
                              },
                            ],
                            qAttrExps: {
                              qValues: [
                                {
                                  qText: '171187.94',
                                  qNum: 171187.94,
                                },
                              ],
                            },
                          },
                          {
                            qText: 'Georgia',
                            qElemNo: 7,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 65473.10999999999,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 36,
                            qSubNodes: [
                              {
                                qText: '65473.11',
                                qElemNo: 0,
                                qValue: 65473.10999999999,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 36,
                                qSubNodes: [],
                              },
                            ],
                            qAttrExps: {
                              qValues: [
                                {
                                  qText: '65473.11',
                                  qNum: 65473.10999999999,
                                },
                              ],
                            },
                          },
                          {
                            qText: 'South Carolina',
                            qElemNo: 36,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 0,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 37,
                            qSubNodes: [
                              {
                                qText: '0',
                                qElemNo: 0,
                                qValue: 0,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 37,
                                qSubNodes: [],
                              },
                            ],
                            qAttrExps: {
                              qValues: [
                                {
                                  qText: '0',
                                  qNum: 0,
                                },
                              ],
                            },
                          },
                        ],
                      },
                      {
                        qText: 'Northeast',
                        qElemNo: 2,
                        qValue: 'NaN',
                        qType: 'N',
                        qMaxPos: 4082652.1300000004,
                        qMinNeg: 0,
                        qUp: 0,
                        qDown: 0,
                        qRow: 38,
                        qSubNodes: [
                          {
                            qElemNo: -1,
                            qValue: 'NaN',
                            qType: 'T',
                            qMaxPos: 3961974.1500000013,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 38,
                            qSubNodes: [
                              {
                                qText: '3961974.15',
                                qElemNo: 0,
                                qValue: 3961974.1500000013,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 38,
                                qSubNodes: [],
                              },
                            ],
                            qAttrExps: {
                              qValues: [
                                {
                                  qText: '3961974.15',
                                  qNum: 3961974.1500000013,
                                },
                              ],
                            },
                          },
                          {
                            qText: 'Virginia',
                            qElemNo: 41,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 2064943.7299999997,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 39,
                            qSubNodes: [
                              {
                                qText: '2064943.73',
                                qElemNo: 0,
                                qValue: 2064943.7299999997,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 39,
                                qSubNodes: [],
                              },
                            ],
                            qAttrExps: {
                              qValues: [
                                {
                                  qText: '2064943.73',
                                  qNum: 2064943.7299999997,
                                },
                              ],
                            },
                          },
                          {
                            qText: 'New York',
                            qElemNo: 30,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 657298.8900000001,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 40,
                            qSubNodes: [
                              {
                                qText: '657298.89',
                                qElemNo: 0,
                                qValue: 657298.8900000001,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 40,
                                qSubNodes: [],
                              },
                            ],
                            qAttrExps: {
                              qValues: [
                                {
                                  qText: '657298.89',
                                  qNum: 657298.8900000001,
                                },
                              ],
                            },
                          },
                          {
                            qText: 'Pennsylvania',
                            qElemNo: 34,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 342186.1299999999,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 41,
                            qSubNodes: [
                              {
                                qText: '342186.13',
                                qElemNo: 0,
                                qValue: 342186.1299999999,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 41,
                                qSubNodes: [],
                              },
                            ],
                            qAttrExps: {
                              qValues: [
                                {
                                  qText: '342186.13',
                                  qNum: 342186.1299999999,
                                },
                              ],
                            },
                          },
                          {
                            qText: 'Maine',
                            qElemNo: 18,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 271166.99,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 42,
                            qSubNodes: [
                              {
                                qText: '271166.99',
                                qElemNo: 0,
                                qValue: 271166.99,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 42,
                                qSubNodes: [],
                              },
                            ],
                            qAttrExps: {
                              qValues: [
                                {
                                  qText: '271166.99',
                                  qNum: 271166.99,
                                },
                              ],
                            },
                          },
                          {
                            qText: 'New Jersey',
                            qElemNo: 27,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 265462.93999999994,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 43,
                            qSubNodes: [
                              {
                                qText: '265462.94',
                                qElemNo: 0,
                                qValue: 265462.93999999994,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 43,
                                qSubNodes: [],
                              },
                            ],
                            qAttrExps: {
                              qValues: [
                                {
                                  qText: '265462.94',
                                  qNum: 265462.93999999994,
                                },
                              ],
                            },
                          },
                          {
                            qText: 'Rhode Island',
                            qElemNo: 35,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 194754.41,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 44,
                            qSubNodes: [
                              {
                                qText: '194754.41',
                                qElemNo: 0,
                                qValue: 194754.41,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 44,
                                qSubNodes: [],
                              },
                            ],
                            qAttrExps: {
                              qValues: [
                                {
                                  qText: '194754.41',
                                  qNum: 194754.41,
                                },
                              ],
                            },
                          },
                          {
                            qText: 'Manitoba',
                            qElemNo: 16,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 120677.98000000001,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 45,
                            qSubNodes: [
                              {
                                qText: '120677.98',
                                qElemNo: 0,
                                qValue: 120677.98000000001,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 45,
                                qSubNodes: [],
                              },
                            ],
                            qAttrExps: {
                              qValues: [
                                {
                                  qText: '120677.98',
                                  qNum: 120677.98000000001,
                                },
                              ],
                            },
                          },
                          {
                            qText: 'Massachusetts',
                            qElemNo: 15,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 120677.98000000001,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 46,
                            qSubNodes: [
                              {
                                qText: '120677.98',
                                qElemNo: 0,
                                qValue: 120677.98000000001,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 46,
                                qSubNodes: [],
                              },
                            ],
                            qAttrExps: {
                              qValues: [
                                {
                                  qText: '120677.98',
                                  qNum: 120677.98000000001,
                                },
                              ],
                            },
                          },
                          {
                            qText: 'Maryland',
                            qElemNo: 17,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 26667.21,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 47,
                            qSubNodes: [
                              {
                                qText: '26667.21',
                                qElemNo: 0,
                                qValue: 26667.21,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 47,
                                qSubNodes: [],
                              },
                            ],
                            qAttrExps: {
                              qValues: [
                                {
                                  qText: '26667.21',
                                  qNum: 26667.21,
                                },
                              ],
                            },
                          },
                          {
                            qText: 'New Hampshire',
                            qElemNo: 26,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 18815.870000000003,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 48,
                            qSubNodes: [
                              {
                                qText: '18815.87',
                                qElemNo: 0,
                                qValue: 18815.870000000003,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 48,
                                qSubNodes: [],
                              },
                            ],
                            qAttrExps: {
                              qValues: [
                                {
                                  qText: '18815.87',
                                  qNum: 18815.870000000003,
                                },
                              ],
                            },
                          },
                          {
                            qText: 'West Virginia',
                            qElemNo: 44,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 0,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 49,
                            qSubNodes: [
                              {
                                qText: '0',
                                qElemNo: 0,
                                qValue: 0,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 49,
                                qSubNodes: [],
                              },
                            ],
                            qAttrExps: {
                              qValues: [
                                {
                                  qText: '0',
                                  qNum: 0,
                                },
                              ],
                            },
                          },
                        ],
                      },
                    ],
                  },
                ],
                qArea: {
                  qLeft: 0,
                  qTop: 0,
                  qWidth: 2,
                  qHeight: 4,
                },
              },
            ],
            qMode: 'K',
            qNoOfLeftDims: 2,
            qIndentMode: true,
            qTreeNodesOnDim: [],
            qColumnOrder: [],
          },
          script: '',
          showTitles: true,
          title: 'Multi Scenario 8',
          subtitle: '',
          footnote: '',
          disableNavMenu: false,
          showDetails: false,
          showDetailsExpression: false,
          showDisclaimer: true,
          labels: {
            auto: true,
            headers: true,
            overlay: true,
            leaves: true,
            values: false,
          },
          color: {
            auto: false,
            mode: 'byMeasure',
            formatting: {
              numFormatFromTemplate: true,
            },
            useBaseColors: 'off',
            paletteColor: {
              index: 6,
            },
            useDimColVal: true,
            useMeasureGradient: true,
            persistent: false,
            expressionIsColor: true,
            expressionLabel: '',
            measureScheme: 'sg',
            reverseScheme: true,
            dimensionScheme: '12',
            autoMinMax: true,
            measureMin: 0,
            measureMax: 10,
            altLabel: 'Sum([Actual Amount])',
            byMeasureDef: {
              label: 'Sum([Actual Amount])',
              key: 'Sum([Actual Amount])',
              type: 'expression',
              activeMeasureIndex: 0,
            },
          },
          legend: {
            show: true,
            dock: 'auto',
            showTitle: true,
          },
          tooltip: {
            auto: true,
            hideBasic: false,
            chart: {
              style: {
                size: 'medium',
              },
            },
            title: '',
            description: '',
          },
          visualization: 'treemap',
          version: '1.2.0',
        };
      },
      getEffectiveProperties: {},
    },
  ],
});
