export default () => ({
  instanceConfig: {
    context: {
      theme: 'senseish',
    },
  },
  genericObjects: [
    {
      getLayout() {
        return {
          qInfo: {
            qId: 'LzUaP',
            qType: 'treemap',
          },
          qMeta: {
            privileges: ['read', 'update', 'delete'],
          },
          qSelectionInfo: {},
          qHyperCube: {
            qSize: {
              qcx: 1,
              qcy: 16,
            },
            qDimensionInfo: [
              {
                qFallbackTitle: 'Country',
                qApprMaxGlyphCount: 7,
                qCardinal: 3,
                qSortIndicator: 'A',
                qGroupFallbackTitles: ['Country'],
                qGroupPos: 0,
                qStateCounts: {
                  qLocked: 0,
                  qSelected: 0,
                  qOption: 3,
                  qDeselected: 0,
                  qAlternative: 0,
                  qExcluded: 0,
                  qSelectedExcluded: 0,
                  qLockedExcluded: 0,
                },
                qTags: ['$ascii', '$text', '$geoname', '$relates_Sheet1.Country_GeoInfo'],
                qDimensionType: 'D',
                qGrouping: 'N',
                qNumFormat: {
                  qType: 'R',
                  qnDec: 14,
                  qUseThou: 1,
                  qFmt: '##############',
                  qDec: '.',
                },
                qIsAutoFormat: true,
                qGroupFieldDefs: ['Country'],
                qMin: 'NaN',
                qMax: 'NaN',
                qAttrExprInfo: [],
                qAttrDimInfo: [],
                qCardinalities: {
                  qCardinal: 3,
                  qHypercubeCardinal: 4,
                  qAllValuesCardinal: -1,
                },
                autoSort: true,
                cId: 'hnZr',
                othersLabel: 'Others',
              },
              {
                qFallbackTitle: 'City',
                qApprMaxGlyphCount: 10,
                qCardinal: 10,
                qSortIndicator: 'A',
                qGroupFallbackTitles: ['City'],
                qGroupPos: 0,
                qStateCounts: {
                  qLocked: 0,
                  qSelected: 0,
                  qOption: 10,
                  qDeselected: 0,
                  qAlternative: 0,
                  qExcluded: 0,
                  qSelectedExcluded: 0,
                  qLockedExcluded: 0,
                },
                qTags: ['$ascii', '$text', '$geoname', '$relates_Sheet1.City_GeoInfo'],
                qDimensionType: 'D',
                qGrouping: 'N',
                qNumFormat: {
                  qType: 'R',
                  qnDec: 14,
                  qUseThou: 1,
                  qFmt: '##############',
                  qDec: '.',
                },
                qIsAutoFormat: true,
                qGroupFieldDefs: ['City'],
                qMin: 'NaN',
                qMax: 'NaN',
                qAttrExprInfo: [],
                qAttrDimInfo: [],
                qCardinalities: {
                  qCardinal: 10,
                  qHypercubeCardinal: 12,
                  qAllValuesCardinal: -1,
                },
                autoSort: true,
                cId: 'pHvwRaX',
                othersLabel: 'Others',
              },
            ],
            qMeasureInfo: [
              {
                qFallbackTitle: 'Avg(Pop)',
                qApprMaxGlyphCount: 2,
                qCardinal: 0,
                qSortIndicator: 'D',
                qNumFormat: {
                  qType: 'R',
                  qnDec: 0,
                  qUseThou: 0,
                  qFmt: '########',
                  qDec: '.',
                  qThou: ',',
                },
                qMin: 1,
                qMax: 22,
                qIsAutoFormat: true,
                qAttrExprInfo: [],
                qAttrDimInfo: [],
                qTrendLines: [],
                autoSort: true,
                cId: 'znqaG',
                numFormatFromTemplate: true,
              },
            ],
            qEffectiveInterColumnSortOrder: [0, 1],
            qGrandTotalRow: [],
            qDataPages: [],
            qPivotDataPages: [],
            qStackedDataPages: [
              {
                qData: [
                  {
                    qElemNo: 0,
                    qValue: 0,
                    qType: 'R',
                    qMaxPos: 127,
                    qMinNeg: 0,
                    qUp: 0,
                    qDown: 0,
                    qRow: 0,
                    qSubNodes: [
                      {
                        qText: '-',
                        qElemNo: -2,
                        qValue: 'NaN',
                        qType: 'U',
                        qMaxPos: 6,
                        qMinNeg: 0,
                        qUp: 0,
                        qDown: 0,
                        qRow: 0,
                        qSubNodes: [
                          {
                            qElemNo: -1,
                            qValue: 'NaN',
                            qType: 'T',
                            qMaxPos: 3,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 0,
                            qSubNodes: [
                              {
                                qText: '3',
                                qElemNo: 0,
                                qValue: 3,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 0,
                                qSubNodes: [],
                              },
                            ],
                          },
                          {
                            qText: '-',
                            qElemNo: -2,
                            qValue: 'NaN',
                            qType: 'U',
                            qMaxPos: 5,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 1,
                            qSubNodes: [
                              {
                                qText: '5',
                                qElemNo: 0,
                                qValue: 5,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 1,
                                qSubNodes: [],
                              },
                            ],
                          },
                          {
                            qText: 'umea',
                            qElemNo: 3,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 1,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 2,
                            qSubNodes: [
                              {
                                qText: '1',
                                qElemNo: 0,
                                qValue: 1,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 2,
                                qSubNodes: [],
                              },
                            ],
                          },
                        ],
                      },
                      {
                        qText: 'Denmark',
                        qElemNo: 2,
                        qValue: 'NaN',
                        qType: 'N',
                        qMaxPos: 26,
                        qMinNeg: 0,
                        qUp: 0,
                        qDown: 0,
                        qRow: 3,
                        qSubNodes: [
                          {
                            qElemNo: -1,
                            qValue: 'NaN',
                            qType: 'T',
                            qMaxPos: 13,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 3,
                            qSubNodes: [
                              {
                                qText: '13',
                                qElemNo: 0,
                                qValue: 13,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 3,
                                qSubNodes: [],
                              },
                            ],
                          },
                          {
                            qText: 'Copenhagen',
                            qElemNo: 8,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 22,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 4,
                            qSubNodes: [
                              {
                                qText: '22',
                                qElemNo: 0,
                                qValue: 22,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 4,
                                qSubNodes: [],
                              },
                            ],
                          },
                          {
                            qText: 'Aarhus',
                            qElemNo: 9,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 4,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 5,
                            qSubNodes: [
                              {
                                qText: '4',
                                qElemNo: 0,
                                qValue: 4,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 5,
                                qSubNodes: [],
                              },
                            ],
                          },
                        ],
                      },
                      {
                        qText: 'Sweden',
                        qElemNo: 0,
                        qValue: 'NaN',
                        qType: 'N',
                        qMaxPos: 65,
                        qMinNeg: 0,
                        qUp: 0,
                        qDown: 0,
                        qRow: 6,
                        qSubNodes: [
                          {
                            qElemNo: -1,
                            qValue: 'NaN',
                            qType: 'T',
                            qMaxPos: 13,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 6,
                            qSubNodes: [
                              {
                                qText: '13',
                                qElemNo: 0,
                                qValue: 13,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 6,
                                qSubNodes: [],
                              },
                            ],
                          },
                          {
                            qText: 'Malmo',
                            qElemNo: 0,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 20,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 7,
                            qSubNodes: [
                              {
                                qText: '20',
                                qElemNo: 0,
                                qValue: 20,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 7,
                                qSubNodes: [],
                              },
                            ],
                          },
                          {
                            qText: 'Ystad',
                            qElemNo: 1,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 20,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 8,
                            qSubNodes: [
                              {
                                qText: '20',
                                qElemNo: 0,
                                qValue: 20,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 8,
                                qSubNodes: [],
                              },
                            ],
                          },
                          {
                            qText: 'Stockholm',
                            qElemNo: 2,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 15,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 9,
                            qSubNodes: [
                              {
                                qText: '15',
                                qElemNo: 0,
                                qValue: 15,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 9,
                                qSubNodes: [],
                              },
                            ],
                          },
                          {
                            qText: 'Gothemburg',
                            qElemNo: 4,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 5,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 10,
                            qSubNodes: [
                              {
                                qText: '5',
                                qElemNo: 0,
                                qValue: 5,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 10,
                                qSubNodes: [],
                              },
                            ],
                          },
                          {
                            qText: 'Uppsala',
                            qElemNo: 5,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 5,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 11,
                            qSubNodes: [
                              {
                                qText: '5',
                                qElemNo: 0,
                                qValue: 5,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 11,
                                qSubNodes: [],
                              },
                            ],
                          },
                        ],
                      },
                      {
                        qText: 'Norway',
                        qElemNo: 1,
                        qValue: 'NaN',
                        qType: 'N',
                        qMaxPos: 30,
                        qMinNeg: 0,
                        qUp: 0,
                        qDown: 0,
                        qRow: 12,
                        qSubNodes: [
                          {
                            qElemNo: -1,
                            qValue: 'NaN',
                            qType: 'T',
                            qMaxPos: 10,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 12,
                            qSubNodes: [
                              {
                                qText: '10',
                                qElemNo: 0,
                                qValue: 10,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 12,
                                qSubNodes: [],
                              },
                            ],
                          },
                          {
                            qText: '-',
                            qElemNo: -2,
                            qValue: 'NaN',
                            qType: 'U',
                            qMaxPos: 7,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 13,
                            qSubNodes: [
                              {
                                qText: '7',
                                qElemNo: 0,
                                qValue: 7,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 13,
                                qSubNodes: [],
                              },
                            ],
                          },
                          {
                            qText: 'Bergen',
                            qElemNo: 7,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 13,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 14,
                            qSubNodes: [
                              {
                                qText: '13',
                                qElemNo: 0,
                                qValue: 13,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 14,
                                qSubNodes: [],
                              },
                            ],
                          },
                          {
                            qText: 'Oslo',
                            qElemNo: 6,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 10,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 15,
                            qSubNodes: [
                              {
                                qText: '10',
                                qElemNo: 0,
                                qValue: 10,
                                qType: 'V',
                                qMaxPos: 0,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 15,
                                qSubNodes: [],
                              },
                            ],
                          },
                        ],
                      },
                    ],
                  },
                ],
                qArea: {
                  qLeft: 0,
                  qTop: 0,
                  qWidth: 2,
                  qHeight: 4,
                },
              },
            ],
            qMode: 'K',
            qNoOfLeftDims: 2,
            qIndentMode: true,
            qTreeNodesOnDim: [],
            qColumnOrder: [0, 1, 2],
          },
          script: '',
          showTitles: true,
          title: '',
          subtitle: '',
          footnote: '',
          disableNavMenu: false,
          showDetails: false,
          showDetailsExpression: false,
          showDisclaimer: true,
          labels: {
            auto: true,
            headers: true,
            overlay: true,
            leaves: true,
            values: false,
          },
          color: {
            auto: true,
            mode: 'primary',
            formatting: {
              numFormatFromTemplate: true,
            },
            useBaseColors: 'off',
            paletteColor: {
              index: 6,
            },
            useDimColVal: true,
            useMeasureGradient: true,
            persistent: true,
            expressionIsColor: true,
            expressionLabel: '',
            measureScheme: 'sg',
            reverseScheme: false,
            dimensionScheme: '12',
            autoMinMax: true,
            measureMin: 0,
            measureMax: 10,
          },
          legend: {
            show: true,
            dock: 'auto',
            showTitle: true,
          },
          tooltip: {
            auto: true,
            hideBasic: false,
            chart: {
              style: {
                size: 'medium',
              },
            },
            data: {},
          },
          visualization: 'treemap',
        };
      },
      getEffectiveProperties: {},
    },
  ],
});
