export default () => ({
  instanceConfig: {
    context: {
      theme: 'senseish',
    },
  },
  genericObjects: [
    {
      getLayout() {
        return {
          qInfo: {
            qId: 'pfncX',
            qType: 'treemap',
          },
          qMeta: {
            privileges: ['read', 'update', 'delete', 'exportdata'],
          },
          qSelectionInfo: {},
          qHyperCube: {
            qSize: {
              qcx: 1,
              qcy: 6,
            },
            qDimensionInfo: [
              {
                qFallbackTitle: 'Dim2',
                qApprMaxGlyphCount: 1,
                qCardinal: 6,
                qSortIndicator: 'A',
                qGroupFallbackTitles: ['Dim2'],
                qGroupPos: 0,
                qStateCounts: {
                  qLocked: 0,
                  qSelected: 0,
                  qOption: 6,
                  qDeselected: 0,
                  qAlternative: 0,
                  qExcluded: 0,
                  qSelectedExcluded: 0,
                  qLockedExcluded: 0,
                },
                qTags: ['$ascii', '$text'],
                qDimensionType: 'D',
                qGrouping: 'N',
                qNumFormat: {
                  qType: 'U',
                  qnDec: 0,
                  qUseThou: 0,
                },
                qIsAutoFormat: true,
                qGroupFieldDefs: ['Dim2'],
                qMin: 'NaN',
                qMax: 'NaN',
                qAttrExprInfo: [],
                qAttrDimInfo: [
                  {
                    qCardinal: 6,
                    qSize: {
                      qcx: 2,
                      qcy: 6,
                    },
                    qFallbackTitle: 'Dim2',
                    id: 'colorByAlternative',
                    label: 'Dim2',
                  },
                ],
                qCardinalities: {
                  qCardinal: 6,
                  qHypercubeCardinal: 6,
                  qAllValuesCardinal: -1,
                },
                autoSort: true,
                cId: 'yYLJTr',
                othersLabel: 'Others',
              },
            ],
            qMeasureInfo: [
              {
                qFallbackTitle: 'Avg(Expression2)',
                qApprMaxGlyphCount: 6,
                qCardinal: 0,
                qSortIndicator: 'D',
                qNumFormat: {
                  qType: 'F',
                  qnDec: 4,
                  qUseThou: 1,
                  qFmt: '# ##0,0000',
                  qDec: ',',
                  qThou: ' ',
                },
                qMin: 0.12931034482758622,
                qMax: 2.3344481605351173,
                qIsAutoFormat: true,
                qAttrExprInfo: [],
                qAttrDimInfo: [],
                qTrendLines: [],
                autoSort: true,
                cId: 'CMtdTU',
                numFormatFromTemplate: true,
              },
            ],
            qEffectiveInterColumnSortOrder: [0],
            qGrandTotalRow: [],
            qDataPages: [],
            qPivotDataPages: [],
            qStackedDataPages: [
              {
                qData: [
                  {
                    qElemNo: 0,
                    qValue: 0,
                    qType: 'R',
                    qMaxPos: 7.4311321749021,
                    qMinNeg: 0,
                    qUp: 0,
                    qDown: 0,
                    qRow: 0,
                    qSubNodes: [
                      {
                        qText: 'f',
                        qElemNo: 1,
                        qValue: 'NaN',
                        qType: 'N',
                        qMaxPos: 2.3344481605351173,
                        qMinNeg: 0,
                        qUp: 0,
                        qDown: 0,
                        qRow: 0,
                        qSubNodes: [
                          {
                            qText: '2,3344',
                            qElemNo: 0,
                            qValue: 2.3344481605351173,
                            qType: 'V',
                            qMaxPos: 0,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 0,
                            qSubNodes: [],
                          },
                        ],
                        qAttrDims: {
                          qValues: [
                            {
                              qText: 'f',
                              qElemNo: 1,
                            },
                          ],
                        },
                      },
                      {
                        qText: 'e',
                        qElemNo: 5,
                        qValue: 'NaN',
                        qType: 'N',
                        qMaxPos: 1.915014164305949,
                        qMinNeg: 0,
                        qUp: 0,
                        qDown: 0,
                        qRow: 1,
                        qSubNodes: [
                          {
                            qText: '1,9150',
                            qElemNo: 0,
                            qValue: 1.915014164305949,
                            qType: 'V',
                            qMaxPos: 0,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 1,
                            qSubNodes: [],
                          },
                        ],
                        qAttrDims: {
                          qValues: [
                            {
                              qText: 'e',
                              qElemNo: 5,
                            },
                          ],
                        },
                      },
                      {
                        qText: 'd',
                        qElemNo: 2,
                        qValue: 'NaN',
                        qType: 'N',
                        qMaxPos: 1.427710843373494,
                        qMinNeg: 0,
                        qUp: 0,
                        qDown: 0,
                        qRow: 2,
                        qSubNodes: [
                          {
                            qText: '1,4277',
                            qElemNo: 0,
                            qValue: 1.427710843373494,
                            qType: 'V',
                            qMaxPos: 0,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 2,
                            qSubNodes: [],
                          },
                        ],
                        qAttrDims: {
                          qValues: [
                            {
                              qText: 'd',
                              qElemNo: 2,
                            },
                          ],
                        },
                      },
                      {
                        qText: 'c',
                        qElemNo: 3,
                        qValue: 'NaN',
                        qType: 'N',
                        qMaxPos: 1.0408163265306123,
                        qMinNeg: 0,
                        qUp: 0,
                        qDown: 0,
                        qRow: 3,
                        qSubNodes: [
                          {
                            qText: '1,0408',
                            qElemNo: 0,
                            qValue: 1.0408163265306123,
                            qType: 'V',
                            qMaxPos: 0,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 3,
                            qSubNodes: [],
                          },
                        ],
                        qAttrDims: {
                          qValues: [
                            {
                              qText: 'c',
                              qElemNo: 3,
                            },
                          ],
                        },
                      },
                      {
                        qText: 'b',
                        qElemNo: 4,
                        qValue: 'NaN',
                        qType: 'N',
                        qMaxPos: 0.5838323353293413,
                        qMinNeg: 0,
                        qUp: 0,
                        qDown: 0,
                        qRow: 4,
                        qSubNodes: [
                          {
                            qText: '0,5838',
                            qElemNo: 0,
                            qValue: 0.5838323353293413,
                            qType: 'V',
                            qMaxPos: 0,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 4,
                            qSubNodes: [],
                          },
                        ],
                        qAttrDims: {
                          qValues: [
                            {
                              qText: 'b',
                              qElemNo: 4,
                            },
                          ],
                        },
                      },
                      {
                        qText: 'a',
                        qElemNo: 0,
                        qValue: 'NaN',
                        qType: 'N',
                        qMaxPos: 0.12931034482758622,
                        qMinNeg: 0,
                        qUp: 0,
                        qDown: 0,
                        qRow: 5,
                        qSubNodes: [
                          {
                            qText: '0,1293',
                            qElemNo: 0,
                            qValue: 0.12931034482758622,
                            qType: 'V',
                            qMaxPos: 0,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 5,
                            qSubNodes: [],
                          },
                        ],
                        qAttrDims: {
                          qValues: [
                            {
                              qText: 'a',
                              qElemNo: 0,
                            },
                          ],
                        },
                      },
                    ],
                  },
                ],
                qArea: {
                  qLeft: 0,
                  qTop: 0,
                  qWidth: 1,
                  qHeight: 6,
                },
              },
            ],
            qMode: 'K',
            qNoOfLeftDims: 1,
            qIndentMode: true,
            qTreeNodesOnDim: [],
            qColumnOrder: [],
          },
          script: '',
          showTitles: true,
          title: '',
          subtitle: '',
          footnote: '',
          disableNavMenu: false,
          showDetails: false,
          showDetailsExpression: false,
          showDisclaimer: true,
          labels: {
            auto: true,
            headers: true,
            overlay: true,
            leaves: true,
            values: false,
          },
          color: {
            auto: false,
            mode: 'byDimension',
            formatting: {
              numFormatFromTemplate: true,
            },
            useBaseColors: 'off',
            paletteColor: {
              index: 6,
            },
            useDimColVal: true,
            useMeasureGradient: true,
            persistent: true,
            expressionIsColor: true,
            expressionLabel: '',
            measureScheme: 'sg',
            reverseScheme: false,
            dimensionScheme: '12',
            autoMinMax: true,
            measureMin: 0,
            measureMax: 10,
            altLabel: 'Dim2',
            byDimDef: {
              label: 'Dim2',
              key: 'Dim2',
              type: 'expression',
              activeDimensionIndex: 0,
            },
          },
          legend: {
            show: true,
            dock: 'auto',
            showTitle: true,
          },
          tooltip: {
            auto: true,
            hideBasic: false,
            chart: {
              style: {
                size: 'medium',
              },
            },
          },
          visualization: 'treemap',
        };
      },
      getEffectiveProperties: {},
    },
  ],
});
