# Run on a branch to verify api
name: API Governance Check [Experimental]

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/yarn_install
      - name: Set version
        run: |
          VER=`node ./tools/get-pre-next-version.js`
          echo "VER=${VER}" >> $GITHUB_ENV

      - name: Prepare API Compliance
        run: |
          docker pull ghcr.io/qlik-download/api-compliance
          docker create -v /specs --name specs alpine:3.4 /bin/true
          docker cp ./api-spec/spec.json  specs:/specs

      - name: Run API Compliance
        run: |
          VER=${{ env.VER }}

          docker run --volumes-from specs \
            -e SPEC_PATHS="6ef0f3ff-3862-442b-8f18-789b5818bdd5@/specs/spec.json" \
            -e COMMIT_SHA="$GITHUB_SHA" \
            -e RELEASE_TAG="$VER" \
            -e PRE_RELEASE="true" \
            -e CREDENTIALS_S3_SECRETKEY="${{ secrets.APICULTURIST_S3 }}" \
            -e CREDENTIALS_GITHUB="${{ secrets.APICULTURIST_GITHUB }}" \
            -e CREDENTIALS_COLONY="${{ secrets.APICULTURIST_TOKEN }}" \
            ghcr.io/qlik-download/api-compliance
