# Run on a branch to update rendering test snapshots
name: Update Snapshots [Experimental]
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update-snapshots:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
      - uses: ./.github/actions/yarn_install
      - run: yarn build
      - run: yarn playwright install --with-deps
      - run: yarn run test:rendering --update-snapshots
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'test: update rendering test screenshots'

