name: verify

on: push

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/yarn_install
      - run: yarn lint
      - run: yarn build
      - run: yarn test
      - run: yarn playwright install --with-deps
      - run: yarn run test:rendering
        id: rendering
      - uses: actions/upload-artifact@v3
        if: ${{ failure() && steps.rendering.conclusion == 'failure' }}
        with:
          name: rendering-output
          path: |
            test/rendering/reports/html/
            test-results/
          retention-days: 3
